.PHONY:  clean


brems1:
	make -f CreBrTab1.mk
brems3:
	make -f CreBrTab3.mk
pair1:
	make -f CrePrTab1.mk
pair2:
	make -f CrePrTab2.mk
pair3:
	make -f CrePrTab3.mk
clean:
	@rm -f *.o core  *~  temp*.f	a.out	\#?*\#
veryclean:
	@rm -f *.o core  *~  temp*.f	*.out	\#?*\#



