#!/bin/csh -f
@ cn = 0
#    if no new volume is defined, use nex
cp epNewVolTemplx.f /tmp/newvol$$

foreach new (`gawk -f ./getnew $1`)
	echo $new
	if($new =~ new-* ) then
	  echo new volume $new defined
        else	
	  echo new volume paraphased as $new
	  @ cn += 1
	  if($cn == 1) then
		  sed -e s/%1/$new/g epNewVolTempl.f > /tmp/newvol$$
		  ###
		    echo ----------first newvol----------
		    cat /tmp/newvol$$
		  ###   
          else
	          gawk -f ./second /tmp/newvol$$ > /tmp/newvol2$$
		  sed -e s/%1/$new/g /tmp/newvol2$$ > /tmp/newvol$$
		  #######		  
             if($cn == 2 ) then
          	  echo ======= newvol2 ---------
		  cat /tmp/newvol2$$
		  echo --------newvol ===========
		  cat /tmp/newvol$$
	     endif	  
                ########
          endif	
       endif	
end
mv /tmp/newvol$$ $EPICSTOP/prog/epNewVolume.f




