.PHONY: all


all: 
	@echo "To clean;  make clean"
test: 
	make -f test.mk
	rm -f /tmp/*.f

clean:
	@rm -f *.o core  *~  *.out

veryclean:
	@rm -f *.o core  *~  temp*.f *.out
rmtemp: 
	@rm  -f temp*.f

