#!/usr/local/bin/tcsh  -f
#   
	if ( $#argv < 3 ) then
		echo "Usage: geteta infile no_of_events outfile"
		exit 1
	endif
	awk 'NR > 3 && $6 != 0  {print $3}' $argv[1] | mkdat -w -5 5 -s 0.2 -n 1 | awk '{$2 = $2/'$argv[2]';print}' > $argv[3]

	exit 0
