#!/bin/csh 
#################################################################
# script to run epos ; argumentS: file name ;  version number
#################################################################

if ( -e $HOME/.epos ) then
source $HOME/.epos
else
source .epos
endif

if ( $OPT == '.' ) then 
    setenv odir `pwd`
else
    setenv odir $OPT
endif


if ( -e $OPT/$1.optns ) then
else
echo $OPT/$1.optns "does not exist"
exit
endif

if ( $?SYSTEM ) then
else
set SYSTEM=`uname`
endif


rm -f $CHK/z-$1.check 
rm -f $CHK/z-$1.data 
rm -f $CHK/z-$1.copy 
rm -f $CHK/z-$1.log 

if ( $HTO == '.' ) then 
    setenv hdir `pwd`
else
    setenv hdir $HTO
endif

setenv seedj `date  '+%N'`
setenv seedi `date  '+%N'`    


#---------------------------------------------------------------------
time $OBJ/$SYSTEM/Xepos -n << END
echo on
!uncomment the following line to get random seed
set seedi $seedi
set seedj $seedj
fname pathnx $EPO/
fname histo  $hdir/$1.histo
fname check  $CHK/z-$1.check
fname copy   $CHK/z-$1.copy
fname log    $CHK/z-$1.log
fname data   $CHK/z-$1.data
fname initl  $EPO/epos.initl
fname inidi  $EPO/epos.inidi              
fname inidr  $EPO/epos.inidr              
fname iniev  $EPO/epos.iniev   
fname inirj  $EPO/epos.inirj
fname inics  $EPO/epos.inics
fname inigrv $EPO/epos.inigrv
fname inihy  $EPO/epos.inihy
fqgsjet dat   $EPO/qgsjet/qgsjet.dat
fqgsjet ncs   $EPO/qgsjet/qgsjet.ncs
fqgsjetII dat   $EPO/qgsjetII/qgsdat-II-03
fqgsjetII ncs   $EPO/qgsjetII/sectnu-II-03
nodecay 120
nodecay -120
nodecay 130
nodecay -130
nodecay -20
nodecay 14
nodecay -14
echo on
input $odir/$1.optns
input  $EPO/epos.param
runprogram
stopprogram
END
if ( -s $CHK/z-$1.data ) then
  mv $CHK/z-$1.data $hdir/$1.data 
  echo "###############################################################"
  echo "      output written to $hdir/$1.data"
  echo "###############################################################"
else
  rm -f $CHK/z-$1.data
endif
if ( -s $CHK/z-$1.check ) then
else
  rm -f $CHK/z-$1.check
endif
if ( -s $hdir/$1.histo ) then
else
  rm -f $hdir/$1.histo
endif
rm -f $CHK/z-$1.log
rm -f $CHK/z-$1.copy
#rm -f gmon.out
date
exit

