#!/bin/bash
# PATH=/bin:/usr/bin:/usr/local/bin:/usr/lang/
# f77-style shell script to compile and load fortran, C, and assembly codes

#	usage:	cppFC [-g] [-O] [-o absfile] [-c] files [-l library]

#		-o objfile	Override default executable name a.out.

#		-c		Do not call linker, leave relocatables in *.o.

#		-S		leave assembler output on file.s

#		-l library	(passed to ld).

#		-u		complain about undeclared variables

#		-w		omit all warning messages

#		-w66		omit Fortran 66 compatibility warning messages

#		files		FORTRAN source files ending in .f .
#				C source files ending in .c .
#				Assembly language files ending in .s .
#				efl source files ending in .e .

#		-D def		passed to C compiler (for .c files)
#                                or cpp for .f files
#		-I includepath	passed to C compiler (for .c files)

#		-Ntnnn		allow nnn entries in table t
##   echo "  cppFC: nparam=$# $*"
s=/tmp/stderr_$$
t=/tmp/f77_$$.o


source $COSMOSTOP/Scrpt/setarch.sh
now=`pwd`
Fmsg=w
#    -noautomatic is essential    
if [ ${now##*/} == "Bertini" ]; then
   FC="f90jx  -O5  -noauto   -f$Fmsg -Am -M$COSMOSTOP/lib/$ARCH"
elif [  ${now##*/}  == "JQMD" ] || [  ${now##*/}  == "PHITS" ] ||  \
 [  ${now##*/}  == "JQMD" ] || [  ${now##*/}  == "nela" ] ||  \
 [  ${now##*/}  == "Com" ] || [ ${now##*/}  == "Xsec" ]; then
    FC="f90jx  -O5  -noauto  -f$Fmsg  -Am -M$COSMOSTOP/lib/$ARCH"
else
   FC="f90jx  -O5  -f$Fmsg -Am -M$COSMOSTOP/lib/$ARCH"
fi
#  full check:  -Haefosux;  first trial was by -O0  -Hefs  
CC=fcc

EFL=${EFL:-/v/bin/efl}
EFLFLAGS=${EFLFLAGS:-'system=portable deltastno=10'}
CPPFLAGS=
rc=0
keeptemp=0
trap "rm -f $s $t; exit \$rc" 0
OUTF=a.out
cOPT=1
CCFLAGS=

while
	test -n "$1"
do
	case "$1"
	in
	-c)	cOPT=0
		shift
		;;

	-D*)	CCFLAGS="$CCFLAGS $1"
	        CPPFLAGS="$CPPFLAGS $1"
		shift 1
		;;

	-g)	FFLAGS="$FFLAGS -g"
		keeptemp=1
		shift;;

        +z)      FFLAGS="$FFLAGS +z"
	        shift
		;;

       +U77)    FFLAGS="$FFLAGS +U77"
	        shift
		;;
   
	-I*)	CPPFLAGS="$CPPFLAGS $1"
		shift
		;;

	-arch)	FFLAGS="$FFLAGS -arch $2"
		shift 2
		;;

	-o)	OUTF=$2
		shift 2
		;;

	-O)	FFLAGS="$FFLAGS -O"
		shift
		;;

	-u)	CPPFLAGS="$CPPFLAGS -u"
		shift
		;;

	-w)	FFLAGS="$FFLAGS -w"
#		case $2 in -6) CPPFLAGS="$CPPFLAGS"66; shift
#			case $2 in -6) shift;; esac;; esac
		shift
		;;

	-N)	CPPFLAGS="$CPPFLAGS $1""$2"
		shift 2
		;;

	-S)	FFLAGS="$FFLAGS -S"
		cOPT=0
		shift
		;;

	*.[fF])
		case "$1" in *.f) f=".f";; *.F) f=".F";; esac
		b=`basename $1 $f`
	        /lib/cpp -C -P  $CPPFLAGS $1  > ./temp$$.f


		case $? in 0);; *) exit;; esac
		echo "*********" $FC
		if [ $1 == "dpmjet3.f" ] || [ $1 == "pythia6115.f" ];then
		    echo "program  is In DPM : " $1 
		    echo "-g is added to the above command"
		    $FC  -c -X9 -g  $FFLAGS ./temp$$.f -o $b.o > $s
		    keeptemp=1 
                elif [ $1 == "jetset74dp.f" ] || [ $1 == "jampyjet.f" ] || [ $1 == "jam.f" ]; then
		    echo "program  is : " $1
		    echo "-g is added to the above command"
		    $FC  -c -X9 -g  $FFLAGS ./temp$$.f -o $b.o > $s
		    keeptemp=1 
		elif [ $1 == "qgprox.f" ]; then 
		    echo "program  is In QGS : " $1
		    echo "-g is added to the above command"
		    $FC  -c -X9 -g  $FFLAGS ./temp$$.f -o $b.o > $s
		    keeptemp=1 
                elif [ $1 == "epos-rsh-lhc-v3700.f" ]; then 
		    echo "program  is In EPOS : " $1
		    echo "-g is added to the above command"
		    $FC  -c -X9 -g  $FFLAGS ./temp$$.f -o $b.o > $s
		    keeptemp=1 
		else
		    $FC  -c -X9   $FFLAGS ./temp$$.f -o $b.o > $s
		fi

	        rm -f temp$$.d
		rc=$?

		case $rc in 0);; *) exit;; esac
		OFILES="$OFILES $b.o"
#		rm $b.c
		if [ $keeptemp = 0 ] ;	then
                  rm ./temp$$.f
		fi
#		rm /tmp/temp$$.f
		case $cOPT in 1) cOPT=2;; esac
		shift
		;;
	*.f90)
		f=".f90"
		b=`basename $1 $f`

	        /lib/cpp -C -P  $CPPFLAGS $1  > ./temp$$.f90
		case $? in 0);; *) exit;; esac
		echo "*********" $FC

                $FC  -c   $FFLAGS ./temp$$.f90 -o $b.o > $s

	        rm -f temp$$.d
		rc=$?

		case $rc in 0);; *) exit;; esac
		OFILES="$OFILES $b.o"
#		rm $b.c
		if [ $keeptemp = 0 ] ;	then
                  rm ./temp$$.f90
		fi
#		rm /tmp/temp$$.f
		case $cOPT in 1) cOPT=2;; esac
		shift
		;;

	*.c)
		echo $1: 1>&2
		OFILE=`basename $1 .c`.o
                $CC -c $CFLAGS $CCFLAGS $1
		rc=$?; case $rc in 0);; *) exit;; esac
		OFILES="$OFILES $OFILE"
		case $cOPT in 1) cOPT=2;; esac
		shift
		;;
	*.o)
		OFILES="$OFILES $1"
		case $cOPT in 1) cOPT=2;; esac
		shift
		;;
	-l)
		OFILES="$OFILES -l$2"
		shift 2
		case $cOPT in 1) cOPT=2;; esac
		;;
	-l*)
		OFILES="$OFILES $1"
		shift
		case $cOPT in 1) cOPT=2;; esac
		;;
	-o)
		OUTF=$2; shift 2;;
	*)
		OFILES="$OFILES $1"
		shift
		case $cOPT in 1) cOPT=2;; esac
		;;
	esac
done

case $cOPT in 2) $FC -o $OUTF -u MAIN__ $OFILES -lf2c -lm;; esac
rc=$?
exit $rc
