#!/usr/local/bin/tcsh -f
#  To invoke cpp and f77 (compile only)

   foreach f ($argv)
	if (-f $f) then
		set src=$f:t
#                             awk is for absoft fortran
		/lib/cpp -I$COSMOSINC $f | awk 'substr($0,1,1) != "#" {print}' -  > ! /tmp/$src; f77  -c /tmp/$src
#		rm /tmp/$src
	endif	
  end
exit (0)




