#!/bin/csh  -f

awk '{if(index($0, "------------------")) {++flag;print} \
      else if( $1 != "c" && $1 != "\!" && flag == 1 ) {  ++cn; $1=cn; print } \
      else print   \
    }' $argv[1]
exit 0

